apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: carservice
  namespace: default
spec:
  host: carservice.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 0
        connectTimeout: 1ms
        tcpKeepalive:
          time: 0s
          interval: 0s
